// <auto-generated />
using System;
using InventoryService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryService.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastRestocked")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinimumStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Linens",
                            Description = "Bath towels",
                            IsActive = true,
                            LastRestocked = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStockLevel = 20,
                            Name = "Towels",
                            QuantityInStock = 100,
                            Supplier = "TowelCo",
                            UnitPrice = 5.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Bathroom Supplies",
                            Description = "Bathroom tissue",
                            IsActive = true,
                            LastRestocked = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStockLevel = 50,
                            Name = "Toilet Paper",
                            QuantityInStock = 200,
                            Supplier = "PaperPlus",
                            UnitPrice = 2.50m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Beverages",
                            Description = "Ground coffee beans",
                            IsActive = true,
                            LastRestocked = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStockLevel = 10,
                            Name = "Coffee",
                            QuantityInStock = 50,
                            Supplier = "CoffeeWorld",
                            UnitPrice = 8.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Cleaning",
                            Description = "Multi-purpose cleaner",
                            IsActive = true,
                            LastRestocked = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStockLevel = 5,
                            Name = "Cleaning Supplies",
                            QuantityInStock = 30,
                            Supplier = "CleanCorp",
                            UnitPrice = 12.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
